# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 7.1
  - 7.2

  # aliased to a recent hhvm version
  # - nightly

install:
  - composer install --ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress
